### ISSUE TITLE
LibreChat cannot be deployed in Guangzhou

### ISSUE THREAD

**Issue by BigTomM** [labring-actions/templates#205]
The librechat template cannot be deployed in the beijing, guangzhou, and hangzhou availability zones of the sealos website. I checked the problem and it is that mongodb is always showing as creating. Is there a way to fix it? Thank you.

this screenshot is from https://gzg.sealos.run/

![image](https://github.com/labring-actions/templates/assets/46660805/26fb20a2-81b2-4f77-9123-ebbe5f9d09c0)

**Comment by zzjin** [comment]
Cannot reproduce.
