### ISSUE TITLE
dify启动不了，现在访问一直报跨域的问题，应该api的服务没有启动

### ISSUE THREAD

**Issue by catdddmouse** [labring-actions/templates#292]
一开始是用的应用部署的dify可以正常使用，然后昨天晚上尝试着更新到0.6.14的版本后，出现了报错，然后就重新改会到0.6.11，
![image](https://github.com/user-attachments/assets/4a3e6f46-c403-4327-97af-d16049688147)
![0d44b7198cfc77c24e1320ae7cccad3](https://github.com/user-attachments/assets/c6beb754-4a8a-4141-b416-49a82fc3ce2f)

后面看下了dify的更新日志，11之后的docker部署不一样了， 多了一个.env文件，所以应该不能升级到.11版本后面，但现在我要回滚到.11之前的版本也不行了，但是我部署一个新的dify，发现也运行不了，一直报跨域的问题

**Comment by catdddmouse** [comment]
![image](https://github.com/user-attachments/assets/9d2952f6-c8e3-43ab-a856-d9a816e94c66)
api服务一直在重启

**Comment by zzjin** [comment]
你好,模板已经更新,可以试试最新版的安装
